### ISSUE TITLE
Broken Instructions/Compatibility Improvements

### ISSUE THREAD

**Issue by OrionNavattan** [cvghivebrain/axm68k#5]
Edited with some additional discoveries.

While porting Sonic 2's sound driver to use AXM68K, I've identified several issues with the Z80 macros that are preventing it from assembling the code:

The macros for the DEC and INC instructions aren't checking for the (hl) register pair. https://github.com/cvghivebrain/axm68k/blob/28e507fcb9f5fe4cee940bf0e56795944437c514/Macros%20-%20More%20CPUs.asm#L235

The SET instruction is unable to use indexed addressing in the source operand.
```set	1,(ix+ch_flags) ; This is valid Z80, but fails to assemble due to lack of support in the macro.```

**Comment by OrionNavattan** [comment]
It appears that the INC instruction also has the same problem.

**Comment by cvghivebrain** [comment]
I think I've fixed it but you'll need to check before I can be sure.

DEC/INC were simple enough to fix. SET is already an instruction in asm68k (as an alternative to =), which I failed to notice when I wrote the macros. I removed it from the exe and added a warning if it's used the original way.

**Comment by OrionNavattan** [comment]
The DEC and INC instructions now work perfectly. However, SET instructions with an indexed address as the source still don't appear to be assembling correctly:
```: set	3,(ix+0)	; AS output: $DDCB, $00DE```

```
   		set	3,(ix+0)	; Set bit 3 (08h) of "playback control" byte (modulation on)
00000EB4                          M 	local	num,num2
00000EB4 =00000003                M 	num:	equ 3
00000EB4 =00000000                M 	num2:	equ (ix+ch_flags)
00000EB4                          M 	getindex	(ix+ch_flags)
00000EB4 =000000DD                M 	ireg:	= $dd
00000EB4 DDCB 00D8                M 	dc.b	ireg,$cb,num2,$c0+(num*8) ; that should be $00DE!
```

I also found another one: ld hl,(n) instructions appear to be very broken:

```ld	hl,(1233h)	; As output: $2A33, $12```
```
00000104                            		ld	hl,(1233h)
00000104                          M 	local	num,num2
00000104                          M 	num:	equ (zdacptrtbl)
00000104 =0000000C                M 	tmp_len:	= strlen("(zdacptrtbl)")
00000104                          M 	tmp_fc:	substr 1,1,"(zdacptrtbl)"
00000104                          M 	tmp_lc:	substr tmp_len,tmp_len,"(zdacptrtbl)"
00000104 ED6B 3312                M 	dc.b	$ed,$6b,num&$ff,num>>8            ; ...what? 
```

Edit: looking more closely, it appears that the macro only accounts for the Z80 extended version of this instruction, and doesn't support the shorter 8080 version that Sonic 2's sound driver uses. I modified the macro to make it to assemble the 8080 version using a switch, although that means only assembling one or the other unless an additional argument is added to allow specifying one or the other.
```
	if strcmp("\tmp_fc","(") & strcmp("\tmp_lc",")") ; ld hl,(n)
	if Assemble8080Ins
	dc.b $2a, num&$ff, num>>8 ; assemble the shorted 8080 version of this instruction
	else
	dc.b $ed, $6b, num&$ff, num>>8 ; otherwise, assemble the extended Z80 version
	endc
	else					; ld hl,n
	dc.b $21, num&$ff, num>>8
	endc
```

**Comment by cvghivebrain** [comment]
I fixed the mistakes in SET and a couple of other instructions. Apparently the shorter versions of ld hl,(n) and ld (n),hl are the "proper" instructions, and the longer versions are undocumented, so I switched to the short versions. I wasn't planning to include undocumented instructions so I'll just leave those ones out, unless someone needs them for some reason.

**Comment by Brainulator9** [comment]
> I wasn't planning to include undocumented instructions so I'll just leave those ones out, unless someone needs them for some reason.

So what exactly will become of anything using ixh, ixl, iyh, and iyl? Or for that matter, sll? Aren't those all undocumented?

**Comment by cvghivebrain** [comment]
If I already added them and they're not interfering with anything, then I'm not going to remove them. I just meant I don't consider them necessary.

**Comment by OrionNavattan** [comment]
The "ld (n),?" one does not occur in Sonic 2's sound driver, but all the others do, and they are all assembling to the correct binary. I'll let you know if I find any other issues.

**Comment by OrionNavattan** [comment]
At this point, I have Sonic 2's driver building bit-perfect with the macros. Only other issue I encountered were a couple of unofficial register synonyms (IXU and IYU for IXH and IYH) which might be worth supporting, since I struggled to find information about them.

**Comment by Brainulator9** [comment]
I think the ixu/iyu thing is explained in the thread at flamewing/asl-releases#2.

**Comment by cvghivebrain** [comment]
Added ixu and iyu, plus some alternate names for SLL.

**Comment by OrionNavattan** [comment]
I've identified a couple issues related to assembler syntax compatibility, as well as another broken instruction.

Although AND, OR, SUB, and XOR only work on A, many assemblers, including AS, VASM, and WinApe's built-in assembler, support an alternate syntax where A is specified as the destination for clarity, e.g., `sub a,(hl)`, `and a,E0h`. This thankfully is an easy fix: these three lines from the ADC under `if cpu_mode=1` allow all four to work with this alternate syntax:		
```
if narg=2 & strcmp("\1","a")
	shift					; ignore a if using alternate syntax
endc
```
The SBC instruction, conversely has the opposite issue: some assemblers allow omitting the destination as a substitute for A, e.g., `sbc a,E0h` can be written as `sbc E0h`. 

Unrelated, at least one assembler (WinApe) allows using decimal 0-7 for the RST slots, as opposed to offsets, e.g., `rst 38h` can be written as `rst 7`. 

Finally, while testing my fix for the first issue, I found a typo in the SUB macro that prevents it from working with ix+n as the source:
https://github.com/cvghivebrain/axm68k/blob/008bb0451f1db224aba067143d2767b61b7b43a1/Macros%20-%20More%20CPUs.asm#L1399

**Comment by cvghivebrain** [comment]
Fixed all the issues you listed. Let me know if I made any mistakes.

**Comment by OrionNavattan** [comment]
Unfortunately, the addition to the rst instruction as written will, as far as I can tell, only work if ASM68K's group functionality is not in use. If groups are in use (as in both of our assemblies), it fails because of the way ASM68K handles label offsets within groups: if you need to use the offset of a label on the first pass while using groups, you must use the offset directive, e.g, offset(\label), otherwise it will not be filled in until the second pass. In this case, this was causing the num>7 conditional to produce an "Expression must evaluate" error if a label or offset was used as the input, as num was not being equated on the first pass.

The best workaround I could think of amounts to using strcmp to explicitly special case 0-7, then using the offset directive if not 0-7. Unfortunately, this assumes that groups are in use, though changing one line in the macro should allow it to work if groups are not in use:

```
rst:		macro
		local num
		if strcmp("\1","0")
			num: = 0
			elseif strcmp("\1","1")
			num: = 1
			elseif strcmp("\1","2")
			num: = 2
			elseif strcmp("\1","3")
			num: = 3
			elseif strcmp("\1","4")
			num: = 4
			elseif strcmp("\1","5")
			num: = 5
			elseif strcmp("\1","6")
			num: = 6
			elseif strcmp("\1","7")
			num: = 7
			else
			num: equ offset(\1) ; change to "equ \1" if not using DualPCM Compress, SoundDriverCompress, or otherwise utilizing sections and groups
		endc
		if num>7
		dc.b $c7+(num&$38)
		else
		dc.b $c7+(num<<3)
		endc
		endm
```

**Comment by cvghivebrain** [comment]
I added a slightly more compact check for 0-7. It can't really be left like this because assembly fails if groups aren't being used. Is there a way to tell if they are? I had a look through the manual and couldn't find one, but maybe there's some kind of trick we could use?

**Comment by OrionNavattan** [comment]
Amazingly enough, I think I found a way to determine if groups are in use by using the **type** function. Bit 1 of the type bitfield indicates that the "symbol is relative to the start of the section;" it is set to 1 if the symbol is a code label within a group/section, or to 0 if it is any other kind of symbol, _or if sections/groups are not in use_.  

After experimenting with it in my disassembly and in an older version of your disassembly where the DAC driver was still assembled separately, the following appears to correctly determine if sections/groups are in use.

```
rst:		macro
		local num
		if (strlen("\1")=1) & instr("01234567","\1")
		num: equ \1
		elseif	((type(\1))&(1<<1))=(1<<1) ; if sections/groups are in use
		num: equ offset(\1)
		else
		num: equ \1
		endc
		if num>7
		dc.b $c7+(num&$38)
		else
		dc.b $c7+(num<<3)
		endc
		endm
```

**Comment by OrionNavattan** [comment]
Found a compatibility improvement that could be made to the ex instruction. While Zilog's documentation only uses the assembler syntaxes `de,hl` and `(sp),rr`, AS doesn't care about the order of the operands in this instruction so long as both form a valid combination (which makes sense given the nature of the instruction), so it'll happily accept `hl,de` and `rr,(sp)`.

The macro should probably be rewritten to not use strcmp on the entire line, as this causes it to fail if there is whitespace in the statement, but for the moment, the following adds:

```
ex:		macro
		if strcmp("\_","af,af")				; ex af,af'
		dc.b 8
		elseif strcmp("\_","(sp),hl")|strcmp("\_","hl,(sp)") ; either order for the operands
		dc.b $e3
		elseif strcmp("\_","(sp),ix")|strcmp("\_","ix,(sp)")
		dc.w $dde3
		elseif strcmp("\_","(sp),iy")|strcmp("\_","iy,(sp)")
		dc.w $fde3
		elseif strcmp("\_","de,hl")|strcmp("\_","hl,de")
		dc.b $eb
		else
		fail
		endc
		endm
```
